---
- hosts: all # Or your specific Kali hosts group
  become: true
  name: Kali System Update with Reboot (Corrected)

  tasks:
    - name: Ping the host
      ping:
      register: ping_result # Register the result HERE, outside the ping task

    - name: Fail if ping fails
      fail:
        msg: "Host 10.1.5.18 is unreachable"
      when: ping_result.ping != "pong"

    - name: Continue with update/upgrade if ping is successful
      block:
        - name: Update apt cache
          apt:
            update_cache: yes
          changed_when: false

        - name: Upgrade Kali packages (including full upgrade)
          apt:
            upgrade: full
          register: apt_result
          failed_when: apt_result.rc is defined and apt_result.rc != 0

        - name: Fail if apt upgrade failed
          fail:
            msg: "Kali package upgrade failed"
          when: apt_result.rc is defined and apt_result.rc != 0

        - name: Ensure Kali metapackage is installed
          apt:
            name: kali-linux-default # Or kali-linux-large, etc.
            state: present

        - name: Remove unused packages
          apt:
            autoremove: yes

        - name: Clean up the package cache
          apt:
            autoclean: yes

        - name: Check if a reboot is required
          command: needs-restarting -r
          register: reboot_check
          changed_when: false
          failed_when: reboot_check.rc > 1 # needs-restarting returns 1 if reboot is needed, 0 if not, >1 if error

        - name: Reboot the server if required
          reboot:
            msg: "Reboot initiated by Ansible for updates"
          when: reboot_check.rc == 1

      when: ping_result.ping == "pong" # Conditionally execute the block
