---
- hosts: all
  become: true
  tasks:
    - name: Erstelle die Datei "ansible_works.check" im Root-Verzeichnis
      file:
        path: /ansible_works.check
        state: touch
        mode: '0644'
